"""Generate documentation pages for packs and schemas.

Outputs:
- docs/reference/packs.md
- docs/reference/schemas.md
- docs/reference/schemas_html/** (HTML generated via json-schema-for-humans, if installed)

This script is intended to be run from the repo root:
  python .\tooling\build_docs.py
"""

from __future__ import annotations

import json
import os
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Iterable


REPO_ROOT = Path(__file__).resolve().parents[1]
PACKS_DIR = REPO_ROOT / "packs"
SCHEMAS_DIR = REPO_ROOT / "schemas"
DOCS_REF_DIR = REPO_ROOT / "docs" / "reference"
SCHEMA_HTML_DIR = DOCS_REF_DIR / "schemas_html"


@dataclass(frozen=True)
class DocItem:
    title: str
    rel_path_posix: str
    description: str | None


def _iter_json_files(root: Path) -> Iterable[Path]:
    yield from sorted(p for p in root.rglob("*.json") if p.is_file())


def _read_json(path: Path) -> dict[str, Any]:
    with path.open("r", encoding="utf-8") as f:
        return json.load(f)


def _posix_rel(path: Path, base: Path) -> str:
    return path.relative_to(base).as_posix()


def _github_file_url(repo_url: str, rel_path_posix: str, ref: str = "main") -> str:
    repo_url = repo_url.rstrip("/")
    return f"{repo_url}/blob/{ref}/{rel_path_posix}"


def _extract_title_and_description(data: dict[str, Any], fallback_title: str) -> tuple[str, str | None]:
    title = data.get("title")
    if isinstance(title, str) and title.strip():
        title_str = title.strip()
    else:
        title_str = fallback_title

    description = data.get("description")
    if isinstance(description, str) and description.strip():
        desc_str: str | None = description.strip()
    else:
        desc_str = None

    return title_str, desc_str


def _group_by_first_segment(items: list[DocItem]) -> dict[str, list[DocItem]]:
    grouped: dict[str, list[DocItem]] = {}
    for item in items:
        first = item.rel_path_posix.split("/", 1)[0]
        grouped.setdefault(first, []).append(item)
    return grouped


def _write_markdown(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def _render_items_md(
    *,
    heading: str,
    items: list[DocItem],
    repo_url: str,
    repo_ref: str,
) -> str:
    grouped = _group_by_first_segment(items)

    lines: list[str] = [f"# {heading}", ""]
    lines.append(f"Generated by `tooling/build_docs.py`. Do not edit by hand.")
    lines.append("")

    for group_name in sorted(grouped.keys()):
        lines.append(f"## {group_name}")
        lines.append("")
        for item in grouped[group_name]:
            file_url = _github_file_url(repo_url, item.rel_path_posix, ref=repo_ref)
            desc = f" — {item.description}" if item.description else ""
            lines.append(f"- [`{item.rel_path_posix}`]({file_url}){desc}")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def _has_json_schema_for_humans() -> bool:
    try:
        import json_schema_for_humans  # noqa: F401

        return True
    except Exception:
        return False


def _generate_schema_html(schema_files: list[Path]) -> bool:
    """Generate HTML docs for each schema file using json-schema-for-humans.

    We call the CLI for compatibility across versions.
    """

    if not _has_json_schema_for_humans():
        print("INFO: json-schema-for-humans not installed; skipping schema HTML generation.")
        return False

    SCHEMA_HTML_DIR.mkdir(parents=True, exist_ok=True)

    for schema_path in schema_files:
        rel = _posix_rel(schema_path, SCHEMAS_DIR)
        out_dir = SCHEMA_HTML_DIR / Path(rel).with_suffix("")
        out_dir.mkdir(parents=True, exist_ok=True)

        # The CLI name is generate-schema-doc (installed by json-schema-for-humans).
        # Output is index.html in the output directory.
        cmd = [
            sys.executable,
            "-m",
            "json_schema_for_humans.generate",
            "--config",
            "{\"show_breadcrumbs\": true, \"copy_css\": true}",
            "--output",
            str(out_dir),
            str(schema_path),
        ]

        try:
            subprocess.run(cmd, check=True, cwd=str(REPO_ROOT), stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
        except subprocess.CalledProcessError as e:
            output = e.stdout.decode("utf-8", errors="replace") if e.stdout else str(e)
            print(f"WARN: Failed generating HTML for {rel}:\n{output}")
            return False

    return True


def main() -> int:
    repo_url = os.environ.get("OPENSCOPE_PARAMS_REPO_URL", "https://github.com/AllenNeuralDynamics/openscope-params")
    repo_ref = os.environ.get("OPENSCOPE_PARAMS_REPO_REF", "main")

    packs: list[DocItem] = []
    for p in _iter_json_files(PACKS_DIR):
        data = _read_json(p)
        title, desc = _extract_title_and_description(data, fallback_title=p.stem)
        packs.append(DocItem(title=title, rel_path_posix=_posix_rel(p, REPO_ROOT), description=desc))

    schemas: list[DocItem] = []
    schema_paths = list(_iter_json_files(SCHEMAS_DIR))
    for s in schema_paths:
        data = _read_json(s)
        title, desc = _extract_title_and_description(data, fallback_title=s.stem)
        schemas.append(DocItem(title=title, rel_path_posix=_posix_rel(s, REPO_ROOT), description=desc))

    DOCS_REF_DIR.mkdir(parents=True, exist_ok=True)

    packs_md = _render_items_md(heading="Packs (reference)", items=packs, repo_url=repo_url, repo_ref=repo_ref)
    schemas_md = _render_items_md(heading="Schemas (reference)", items=schemas, repo_url=repo_url, repo_ref=repo_ref)

    packs_md_path = DOCS_REF_DIR / "packs.md"
    schemas_md_path = DOCS_REF_DIR / "schemas.md"

    _write_markdown(packs_md_path, packs_md)
    _write_markdown(schemas_md_path, schemas_md)

    # Best-effort HTML generation.
    generated_html = _generate_schema_html(schema_paths)
    if generated_html:
        # Add a small hint section in schemas.md for the HTML pages.
        hint = (
            "\n## HTML schema docs (generated)\n\n"
            "This build also generated per-schema HTML under `docs/reference/schemas_html/` "
            "(published in the site as static files).\n"
        )
        _write_markdown(schemas_md_path, (schemas_md.rstrip() + hint + "\n"))

    print(f"Wrote {packs_md_path.relative_to(REPO_ROOT)}")
    print(f"Wrote {schemas_md_path.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
